<a href="https://colab.research.google.com/github/A01199130/-A2-Tipos-de-variables/blob/main/Quiz_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Name that characterizes the dataset:**

Average quarterly monetary current expenditure by federal entity according to major expenditure categories

**2. Organization that generated it**

National Institute of Statistics and Geography (INEGI)

**3. Download link of the dataset:** https://www.inegi.org.mx/app/tabulados/interactivos/?pxq=Hogares_Hogares_12_60ab9bc6-fec2-4737-a8a5-3d3b435398b6&idrt=54&opc=t



 **3.1 CSV file of the dataset:**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [20]:
import pandas as pd
df = pd.read_csv("/content/Average quarterly monetary current expenditure by federal entity according to major expenditure categories(Hoja1).csv", encoding='ISO-8859-1')
df.head(34)

,Entidad federativa,Total,"Alimentos, bebidas y tabaco",Vestido y calzado,"Vivienda, servicios de conservación, energía eléctrica y combustibles","Artículos y servicios para la limpieza, cuidados de la casa, enseres domésticos y muebles, cristalería, utensilios domésticos y blancos",Cuidados de la salud,"Transporte; adquisición, mantenimiento, accesorios y servicios para vehículos; comunicaciones","Servicios de educación, artículos educativos, artículos de esparcimiento y otros gastos de esparcimiento","Cuidados personales, accesorios y efectos personales y otros gastos diversos",Transferencias de gasto
0,Estados Unidos Mexicanos,"47,674","17,982","1,830","4,346","3,014","1,605","9,319","4,593","3,709","1,276"
1,Aguascalientes,"53,870","18,319","1,901","4,572","3,825","1,821","11,748","6,019","4,372","1,292"
2,Baja California,"55,269","19,444","1,769","7,476","3,181","1,129","12,676","4,130","4,658",807
3,Baja California Sur,"55,939","18,559","1,892","6,230","3,525","1,433","12,785","4,337","4,493","2,685"
4,Campeche,"41,574","16,620","1,167","2,894","3,008","1,330","8,433","3,078","3,435","1,609"
5,Coahuila de Zaragoza,"50,501","16,083","1,750","4,828","3,379","1,459","11,185","5,616","4,712","1,489"
6,Colima,"52,016","19,275","1,764","4,350","3,328","2,026","11,671","3,965","3,746","1,890"
7,Chiapas,"27,118","12,605","1,139","1,926","1,864",966,"4,250","1,679","2,185",504
8,Chihuahua,"46,881","15,461","1,872","5,296","3,152","1,283","10,541","4,185","4,241",850
9,Ciudad de México,"66,383","24,389","2,810","7,917","4,310","2,424","10,445","7,515","4,875","1,699"
10,Durango,"42,456","13,924","1,997","2,978","3,014","1,507","9,576","4,332","3,838","1,290"
11,Guanajuato,"45,570","17,126","1,679","3,672","3,153","1,584","8,799","4,710","3,695","1,151"
12,Guerrero,"34,566","14,956","1,180","2,249","2,261","1,705","6,006","2,274","2,802","1,134"
13,Hidalgo,"36,414","14,207","1,448","2,662","2,227","1,597","7,437","3,190","2,610","1,037"
14,Jalisco,"56,015","21,442","2,150","5,362","2,996","1,882","11,215","5,469","4,186","1,312"
15,México,"49,595","21,158","1,896","3,917","2,663","1,246","9,341","4,709","3,414","1,251"
16,Michoacán de Ocampo,"45,651","18,042","2,015","3,204","2,944","2,033","8,479","4,172","3,399","1,361"
17,Morelos,"42,253","16,598","1,434","3,176","2,756","1,638","8,583","3,674","3,075","1,319"
18,Nayarit,"44,717","18,338","1,805","3,515","2,754","1,430","8,431","3,390","3,454","1,599"
19,Nuevo León,"59,192","20,556","1,974","6,398","3,717","1,368","13,288","6,144","4,628","1,119"
20,Oaxaca,"34,107","13,791","1,528","2,006","2,282","2,145","5,982","2,925","2,454",994
21,Puebla,"41,720","15,542","1,999","3,042","2,744","1,496","7,540","4,532","3,491","1,335"
22,Querétaro,"61,593","21,446","2,373","5,959","3,622","2,160","12,503","7,247","4,670","1,614"
23,Quintana Roo,"53,667","20,067","1,623","6,332","3,212","1,214","10,805","4,227","3,978","2,208"
24,San Luis Potosí,"47,045","15,711","1,779","3,635","3,332","2,091","9,256","5,644","3,964","1,632"
25,Sinaloa,"48,557","16,984","1,877","4,929","3,092","1,640","10,665","3,777","4,213","1,381"
26,Sonora,"51,336","16,530","1,914","5,523","3,127","1,767","11,277","4,715","4,390","2,092"
27,Tabasco,"39,508","15,614","1,264","2,234","2,850","1,516","7,979","3,778","3,104","1,169"
28,Tamaulipas,"44,844","15,618","1,589","4,548","3,122","1,373","9,669","4,310","3,600","1,015"
29,Tlaxcala,"40,048","15,268","2,125","2,519","2,386","1,360","7,709","4,373","3,070","1,239"
30,Veracruz de Ignacio de la Llave,"34,461","13,726","1,295","2,883","2,686","1,219","5,924","3,104","2,750",876
31,Yucatán,"51,255","18,874","1,459","3,477","3,361","2,087","11,156","5,135","3,658","2,048"
32,Zacatecas,"39,860","13,975","1,621","3,080","2,703","2,193","8,411","3,456","3,495",927

**4. Description of the dataset:**
The dataset shows the average quarterly household expenditure by state in Mexico, divided into different categories. The information is expressed in Mexican pesos and corresponds to the year 2024, allowing for comparison of consumption patterns across states.

**Characteristics of the dataset:**

rows: 56

columns: 11

units: Pesos MX

Period: 2024

**Categories:**

-Total
-Food, beverages and tobacco
-Clothing and footwear
-Housing, maintenance, electricity and fuels
-Articles and services for cleaning, household care and domestic appliances
-Health care
-Transportation, communications and related services
-Education services, educational articles, recreation and culture
-Personal care and other miscellaneous expenses
-Expenditure transfers

**5. Unclear identifier and how to investigate it:**

An identifier that is not very clear is the category “Articles and services for cleaning, household care and domestic appliances”, since it does not specify which exact products it includes.       

**To investigate it, It could be:**

-Search for a methodological glossary provided by INEGI.

-Consult the technical sheet that accompanies the dataset.

-Analyze the ENIGH microdata, where the codes and classification of each  expenditure category are detailed.

**6. What questions could be answered with this data?**

Which states have a higher percentage of expenditure on food, beverages, and tobacco?

How does spending on health, housing, and transportation vary among states?

Are there major differences in the spending patterns across the regions of the country?

**7. Research question of interest**

Is there a relationship between the level of health expenditure and food expenditure among the states of Mexico?

**8. Skateholders**

**Food and beverage companies:** these seek information to understand demand and consumption habits in different states.

**Academic and research institutions:** interested in analyzing consumption patterns and their relationship with well-being indicators.

**Government:** uses this type of information to design public policies on food, health, and social development.